version: '3.2'
services:
  frontend:
    build: frontend
    ports:
      - '20080:80'
    volumes:
      - '~/.composer-docker/cache:/root/.composer/cache:delegated'
      - './:/app'
  backend:
    build: backend
    ports:
      - '21080:80'
    volumes:
      - '~/.composer-docker/cache:/root/.composer/cache:delegated'
      - './:/app'
  mysql:
    image: 'mysql:5.7'
    environment:
      - MYSQL_ROOT_PASSWORD=verysecret
      - MYSQL_DATABASE=yii2advanced
      - MYSQL_USER=yii2advanced
      - MYSQL_PASSWORD=secret
    volumes:
      - '.\vagrant\mysql:/var/lib/mysql'
    ports:
      - '3306:3306'
      - '33060:33060'
  elasticsearch:
    image: 'elasticsearch:2'
    environment: []
    ports:
      - '9200'
      - '9300'
