version: '3.3'
services:
  mysql:
    image: mysql
    volumes:
      - '.\.docker\db:/var/lib/mysql'
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=webx
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
    links:
      - apache
  apache:
    build: .docker
    network_mode: bridge
    ports:
      - '8080:80'
    volumes:
      - '.:/var/www/html'

